# Site settings
title: Mischa Nistl, DJ
description: "... aus Leidenschaft"
email: djmischanistl@web.de
url: http://www.djmischanistl.de

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Copyright settings
copyright: FW

# Social networks usernames
social:
  - title: instagram
    url: https://www.instagram.com/djmischanistl
  - title: facebook
    url: https://www.facebook.com/mischa.nistl
  - title: soundcloud
    url: https://soundcloud.com/djmischanistl

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics: UA-129043558-1

# jekyll-tidy
jekyll-tidy:
#  exclude: ["index.html"]
  ignore_env: development
  compress_html: true